Repository fsprojects/FSharpPlus, pull requests merged in 2024-06, with the labels that each got.

#592 Add new Issue Templates and Release yamls
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/01_bug_report.yml
  .github/ISSUE_TEMPLATE/02_api_proposal.yml
  .github/ISSUE_TEMPLATE/03_general_feature.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/release.yml
  FSharpPlus.sln
Labels: enhancement

#315 Rename string trim functions
  src/FSharpPlus/Extensions/String.fs
Labels: F#+ v2.0, breaking change

#601 +Branches documentation
  BRANCHES.md
  DEVELOPER_GUIDE.md
Labels: F#+ v1.1
